name: winfetch-py CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
    - main
  
jobs:
  setup-python-and-dependencies:
    name: setup python and dependencies
    runs-on: windows-latest
    steps:

    - name: Checkout repo    
      uses: actions/checkout@v4
      with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
        repository: 'Warrobot10/winfetch-py'
  
    - name: Setup python
      uses: actions/setup-python@v5.1.1
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.12.4
        # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
        cache: pip
        # The target architecture (x86, x64) of the Python or PyPy interpreter.
        architecture: x64
    
  build-executable:
    name: build executable
    runs-on: windows-latest
    steps:

    - name: Run pyinstaller
      run: pyinstaller --onefile D:/a/winfetch-py/winfetch-py
