name: winfetch-py CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
    - main
  
jobs:
  setup-python-and-dependencies:
    name: setup python and dependencies
    runs-on: windows-latest
    steps:

    - name: Checkout repo    
      uses: actions/checkout@v4
      with:
        repository: 'Warrobot10/winfetch-py'
  
    - name: Setup python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.12.4
        cache: pip
        architecture: x64

    - name: Install packages
      run: pip install -r requirements.txt

    - name: Run pyinstaller
      run: pyinstaller --onefile ${{ github.workspace }}/winfetch.py

    - name: Create Output Directory
      run: mkdir -p output

    - name: Run innosetup
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        # Path to input .iss script file
        path: ${{ github.workspace }}/winfetch-setup-build.iss
        
